name: Build

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm i
      - name: Linter Check
        run: npm run lint
      - name: Unit Test
        run: npm run test
      - name: Build Test
        run: npm run build
